spring.application.name=back

# ?? BASE DE DATOS ????????????????????????????????????????????????????????????
# En local usa tu PostgreSQL. En Koyeb configura estas como variables de entorno.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/semana_academica}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# ?? JPA / HIBERNATE ??????????????????????????????????????????????????????????
# validate: Hibernate verifica que las entidades coincidan con la BD pero NO modifica nada.
# Usamos validate porque la BD ya fue creada con el script SQL.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ?? SERVIDOR ?????????????????????????????????????????????????????????????????
server.port=8080

# ?? JWT ??????????????????????????????????????????????????????????????????????
jwt.secret=${JWT_SECRET:semana_academica_secret_key_muy_larga_y_segura_2026}
jwt.expiration=86400000

# ?? OPEN-IN-VIEW (desactivar warning) ????????????????????????????????????????
spring.jpa.open-in-view=false

# ?? SERIALIZACIÓN DE FECHAS ??????????????????????????????????????????????????
# Serializa LocalDate como "2026-12-01" y LocalTime como "08:00:00"
spring.jackson.serialization.write-dates-as-timestamps=false